<?php

return [
    'name'                       => '测试',
    'beian'                      => '',
    'cdnurl'                     => '',
    'version'                    => '1.0.1',
    'timezone'                   => 'Asia/Shanghai',
    'forbiddenip'                => '',
    'languages'                  => [
    ],
    'fixedpage'                  => 'dashboard',
    'categorytype'               => [
        'default' => 'Default',
        'page'    => 'Page',
        'article' => 'Article',
        'test'    => 'Test',
    ],
    'configgroup'                => [
        'basic'      => 'Basic',
        'email'      => 'Email',
        'dictionary' => 'Dictionary',
        'system'     => 'System',
        'order'      => 'Order',
        'dforder'    => 'Dforder',
    ],
    'mail_type'                  => '1',
    'mail_smtp_host'             => 'smtp.qq.com',
    'mail_smtp_port'             => '465',
    'mail_smtp_user'             => '10000',
    'mail_smtp_pass'             => 'password',
    'mail_verify_type'           => '2',
    'mail_from'                  => '10000@qq.com',
    'login_background'           => '/assets/img/qrcode.png',
    'login_background_img'       => '',
    'login_html'                 => 'login',
    'login_checkusergoogle'      => '0',
    'login_checkmerchantgoogle'  => '0',
    'login_checkagentgoogle'     => '0',
    'login_checkadmingoogle'     => '0',
    'loginip_checkuserlogin'     => '0',
    'loginip_checkmerchantlogin' => '0',
    'loginip_checkagentlogin'    => '0',
    'loginip_checkadminlogin'    => '0',
    'order_checkmerchantgoogle'  => '0',
    'agentrate'                  => '0',
    'is_checkvisitip'            => '0',
    'order_checkmerchantpaypwd'  => '0',
    'order_checkmerchantpayip'   => '0',
    'expire_time'                => '10',
    'success_order_time'         => '5',
    'fail_order_time'            => '5',
    'is_queue_notify'            => '0',
    'user_robin_rule'            => '2',
    'qrcode_interval'            => '1',
    'api_domain_name'            => 'mgwgtest.yfndyw.xyz',
    'app_secret'                 => 'grkyUKGop3',
    'acc_robin_rule'             => '2',
    'agent_rate'                 => '0',
    'user_rate'                  => '2',
    'merchant_rate'              => '0',
    'referral'                   => '0',
    'xl_check_order_time'        => '60',
    'cron_deal_data'             => '1',
    'user_pay_num'               => '0',
    //是否开启IP变动检测
    'loginip_admin_check'        => '0',
    'loginip_agent_check'        => '0',
    'loginip_merchant_check'     => '0',
    'loginip_user_check'         => '0',
    //是否同一账号同一时间只能在一个地方登录
    'login_unique_admin'         => '0',
    'login_unique_agent'         => '0',
    'login_unique_merchant'      => '0',
    'login_unique_user'          => '0',
    'my_tg_group_id' => '-1002061853222',
];